# -*- coding: utf-8 -*-
"""Classes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j-_e03eOCvKRf_1xH99tHjQQ8s1TAfOZ
"""

class MyClass: pass

obj = MyClass()
obj.__class__.__name__
'MyClass'

# Functions have a
# similar feature:

def myfunc(): pass

myfunc.__name__