# -*- coding: utf-8 -*-
"""Dispatch_IF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15N3io_P_rpiV9MyGVmx3gKTz8cI4oR8F
"""

def dispatch_if(operator, x, y):
    if operator == 'add':
        return x + y
    elif operator == 'sub':
        return x - y
    elif operator == 'mul':
        return x * y
    elif operator == 'div':
        return x / y
    else:
        return None


def dispatch_dict(operator, x, y):
    return {
        'add': lambda: x + y,
        'sub': lambda: x - y,
        'mul': lambda: x * y,
        'div': lambda: x / y,
    }.get(operator, lambda: None)()

dispatch_if('mul', 2, 8)

dispatch_dict('mul', 2, 8)

dispatch_if('unknown', 2, 8)

dispatch_if('unknown', 2, 8)