# -*- coding: utf-8 -*-
"""Floating Point Literals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ws7dKU92sb-jEl8VfghJ_NW_D4vCw2sn
"""

3.14

314\.  
  # Trailing zero(s) not required

.314    # Leading zero(s) not required.

3e0

3E0     # 'e' or 'E' can be used.

3e1     # Positive value after e moves the decimal to the right.

3e-1    # Negative value after e moves the decimal to the left.

3.14e+2 # '+' not required but can be used for exponent part.