# -*- coding: utf-8 -*-
"""IP Address.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pg1PJ8cSe3V1VFfk2mg_XqHB_jGvF5XH
"""

import ipaddress

ipaddress.ip_address('192.168.1.2')

ipaddress.ip_address('2001:af3::')