# -*- coding: utf-8 -*-
"""issubclass.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14jqt4kMu802w0-M3MGnyS53SphtYyn3c
"""

class BaseClass: pass
class SubClass(BaseClass): pass

issubclass(SubClass, BaseClass)

issubclass(SubClass, object)

issubclass(BaseClass, SubClass)