# -*- coding: utf-8 -*-
"""String encode().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15tp0cuAQlFIf6lBwVwBNcWX-NEQjsdBf

a sample python program is given, which will explain how encode() function will works
"""

our_string = 'åkshay Chopåde'
encoded_string = our_string.encode('utf-8','strict')
encoded_string

"""Lets check the type of our_string"""

type(our_string)

"""Lets check the type of encoded_string"""

type(encoded_string)

"""By default encode() method use 'utf-8' as encoding and 'strict'as errors"""

our_string = 'åkshay Chopåde'
our_string.encode()

"""'backslashreplace' - this type will uses a backslash instead of the character that could not be encoded"""

our_string = 'åkshay Chopåde'
our_string.encode(encoding="ascii",errors="backslashreplace")

"""'ignore' - this type will ignore the characters that cannot be encoded"""

our_string = 'åkshay Chopåde'
our_string.encode(encoding="ascii",errors="ignore")

"""'namereplace' - this type will replace the character with a text explaining the character"""

our_string = 'åkshay Chopåde'
our_string.encode(encoding="ascii",errors="namereplace")

"""'replace' - this type will replace the character with a question mark"""

our_string = 'åkshay Chopåde'
our_string.encode(encoding="ascii",errors="replace")

"""'xmlcharrefreplace' - this type will replace the character with an xml character"""

our_string = 'åkshay Chopåde'
our_string.encode(encoding="ascii",errors="xmlcharrefreplace")

"""'strict' - this type will raise an error on failure"""

our_string = 'åkshay Chopåde'
our_string.encode(encoding="ascii",errors="strict")