# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1llPO5itmcnKoN2Zn84ieKorjcaqu4aj1
"""

class MyClass:
    def method(self):
        return 'instance method called', self

""" '''
        Instance methods need a class instance and
        can access the instance through `self`.
        '''
"""

@classmethod
    def classmethod(cls):
       return 'class method called', cls

""" Class methods don't need a class instance.
        They can't access the instance (self) but
        they have access to the class itself via `cls`.
"""

@staticmethod
    def staticmethod():
       return 'static method called'

""" '''
        Static methods don't have access to `cls` or `self`.
        They work like regular functions but belong to
        the class's namespace.
        '''
"""

obj = MyClass()
obj.method()

"""All methods types can be
called on a class instance:
"""

obj.classmethod()

obj.staticmethod()

"""Calling instance methods fails
if we only have the class object:
"""

MyClass.classmethod()

MyClass.staticmethod()

MyClass.method()